vaxtrace/routes/web.php
<?php

use App\Http\Controllers\Vaxtracing\Auth\AuthController;
use App\Http\Controllers\Vaxtracing\JsonDataController;
use App\Http\Controllers\Vaxtracing\CategoryController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Vaxtracing\PeopleController;
use App\Http\Controllers\Vaxtracing\DashboardController;
use App\Http\Controllers\Vaxtracing\PermissionController;
use App\Http\Controllers\Vaxtracing\RoleController;
use App\Http\Controllers\Vaxtracing\SubCategoryController;
use App\Http\Controllers\Vaxtracing\SubSystemController;
use App\Http\Controllers\Vaxtracing\VaccineeController;
use App\Http\Middleware\AuthCheck;
use App\Models\Vaxtracing\Role;
use App\Models\Vaxtracing\Summary;
use App\Models\Vaxtracing\User;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { 
    if(session()->has('LoggedUser')){
        return redirect('/dashboard');
    }
    return view('index'); 
})->name('home');

// Auth
Route::post("/check", [AuthController::class, "login"])->name('submit-login');

Route::get('/logout', [AuthController::class, "logout"])->name('logout');

Route::get('/user-login', [AuthController::class, "view_login"])->name('view-login');
//MIDDLEWARE
Route::group(['middleware' => ['AuthCheck']],function(){
    

    //DASHBOARD
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('get_admin_dashboard');

    //MANAGER USER
    Route::get('/manage/user',function () {
        abort_if(! session('LoggedUser')->hasPermission('USER_ACCESS'), 403);
        return view('Vaxtracing.admin.ManageUser.index');
    })->name('get_manage_user');
  
    
    Route::resource('people', PeopleController::class);

    Route::get('/create/user', function () {
        abort_if(! session('LoggedUser')->hasPermission('USER_CREATE'), 403);
        $total_role = Role::get();
        return view('Vaxtracing.admin.CreatePerson.index', compact('total_role'));
    })->name('get_create_user');

    Route::get('/update/user', function () {
        abort_if(! session('LoggedUser')->hasPermission('USER_UPDATE'), 403);
        $total_role = Role::get();
        return view('Vaxtracing.admin.UpdatePerson.index', compact('total_role'));
    })->name('get_update_user');

    //Generate address
    Route::get("/create/get_address", [JsonDataController::class, "index"])->name('get_address');

    Route::get("/get-activity-logs", [JsonDataController::class, "getActivity"])->name('get_activity');


    Route::get("/get-vaccinees", [JsonDataController::class, "getVaccinees"])->name('get_vaccinees');

    //Change Password
    Route::post('/change/password/', [PeopleController::class, 'changePassword'])->name('change_password');

    // List of user
    Route::post("/create/people", [PeopleController::class, "store"]);

    Route::get("/show/people", [PeopleController::class, "index"])->name('get_people');

    Route::get("/show/deleted_people", [PeopleController::class, "showDeletedPeople"])->name('get_deleted_people');

    Route::get("/show/restored_people", [PeopleController::class, "showRestoredPeople"])->name('get_restored_people');

    Route::get('/show/people/{user_id?}', [PeopleController::class, 'show'])->name('show_people');

    Route::get('/update/people/{user_id?}', [PeopleController::class, 'edit'])->name('update_people');

    Route::post('/update/people/save/{user_id?}', [PeopleController::class, 'update'])->name('save_update_people');

    Route::post('/delete/people/{user_id?}', [PeopleController::class, 'destroy'])->name('delete_people');

    Route::post('/restore/people/{user_id?}', [PeopleController::class, 'restore'])->name('restore_people');


    Route::view('/edit/profile', 'Vaxtracing.admin.EditProfile.index')->name('edit_profile');

    Route::post('/edit/profile/save/{user_id?}', [PeopleController::class, 'editProfile'])->name('save_edit_profile');

    Route::get('/view/activity_log',  function () {
        abort_if(! session('LoggedUser')->hasPermission('ACTIVITY_ACCESS'), 403);
        return view('Vaxtracing.admin.ActivityLog.index');
    })->name('view_activity_log');

    Route::get('/view/department', function () {
        abort_if(! session('LoggedUser')->hasPermission('ROLE_ACCESS'), 403);
        return view('Vaxtracing.admin.Department.index');
    })->name('view_department');
    
    Route::get('/view/permission', function () {
        abort_if(! session('LoggedUser')->hasPermission('PERMISSION_ACCESS'), 403);
        return view('Vaxtracing.admin.Permission.index');
    })->name('view_permission');

    Route::get('/view/subsystem', function () {
        abort_if(! session('LoggedUser')->hasPermission('SUBSYSTEM_ACCESS'), 403);
        return view('Vaxtracing.admin.Subsystem.index');
    })->name('view_subsystem');

    // Route::view('/create/department', 'Vaxtracing.admin.CreateDepartment.index')->name('get_create_department');

    //Route::view('/create/permission', 'Vaxtracing.admin.CreatePermission.index')->name('get_create_permission');

    //MANAGE PERMISSION

    Route::resource('role', RoleController::class);

    Route::get('/update/role/{id?}', [RoleController::class, 'edit'])->name('update_department');

    Route::post('/update/role/save/{id?}', [RoleController::class, 'update'])->name('save_update_department');

    Route::post('/delete/role/{id?}', [RoleController::class, 'destroy'])->name('delete_department');

    Route::get("/show/role/{id?}", [RoleController::class, "show"])->name('show_role');

    //MANAGE PERMISSION

    Route::resource('permission', PermissionController::class);

    Route::get('/update/permission/{id?}', [PermissionController::class, 'edit'])->name('update_permission');

    Route::post('/update/permission/save/{id?}', [PermissionController::class, 'update'])->name('save_update_permission');

    Route::post('/delete/permission/{id?}', [PermissionController::class, 'destroy'])->name('delete_permission');

    //MANAGE SUBSYSTEM

    Route::resource('subsystem', SubSystemController::class);

    Route::get('/update/subsystem/{id?}', [SubSystemController::class, 'edit'])->name('update_subsystem');

    Route::post('/update/subsystem/save/{id?}', [SubSystemController::class, 'update'])->name('save_update_subsystem');

    Route::post('/delete/subsystem/{id?}', [SubSystemController::class, 'destroy'])->name('delete_subsystem');


    //TRACKER MAIN SYSTEM

    Route::get('/view/Tracker-Main-System/vaccinees/VaccineeMasterList', function () {
        abort_if(! session('LoggedUser')->hasPermission('VACCINEE_ACCESS'), 403);
        $summaries = DB::table('transaction_has_summary')->select('assist_by')->distinct()->get();
       
        return view('Vaxtracing.admin.TrackingSystem.VaccineeMasterList.index', compact('summaries'));
    })->name('view_vaccinees_VaccineeMasterList');
    

    Route::resource('vaccinee', VaccineeController::class);

    Route::post('/update/vaccinee/save/{id?}', [VaccineeController::class, 'update'])->name('save_update_vaccinee');

    Route::post('/delete/vaccinee/{id?}', [VaccineeController::class, 'destroy'])->name('delete_vaccinee');

    Route::get('/show/vaccinee/{id?}', [VaccineeController::class, 'show'])->name('show_vaccinee');

    Route::get('/monitor/vaccinee/{id?}', [VaccineeController::class, 'monitor'])->name('monitor_vaccinee');

    Route::get('/show/summary/{id?}', [VaccineeController::class, 'showSummary'])->name('show_summary');

    Route::get('/show/transaction/{vaccinee_id?}/{id?}', [VaccineeController::class, 'showTransaction'])->name('show_transaction');

    Route::post('/save/vaccinee/transaction', [VaccineeController::class, 'saveTransaction'])->name('save_vaccinee_transaction');

    Route::post('/save/update/vaccinee/transaction', [VaccineeController::class, 'saveUpdateTransaction'])->name('save_update_transaction');

    Route::get('/show/all/summary/{date_from?}/{date_to?}', [VaccineeController::class, 'showSummaryLogs'])->name('show_summary_logs');

    Route::get('/view/Tracker-Main-System/vaccinees/status/category', function () {
        return view('Vaxtracing.admin.TrackingSystem.Category.index');
    })->name('view_vaccinees_status_category');

    Route::resource('category', CategoryController::class);

    Route::post('/update/category/save/{id?}', [CategoryController::class, 'update'])->name('save_update_category');

    Route::post('/delete/category/{id?}', [CategoryController::class, 'destroy'])->name('delete_category');

    Route::get('/show/category/{id?}', [CategoryController::class, 'show'])->name('show_category');

    Route::get('/view/Tracker-Main-System/vaccinees/status/sub-category/{category_id?}', function ($category_id) {
        session()->put('current_category', $category_id);
        return view('Vaxtracing.admin.TrackingSystem.SubCategory.index',compact('category_id'));
    })->name('view_vaccinees_status_sub-category');

    Route::resource('sub_category', SubCategoryController::class);

    Route::post('/update/sub_category/save/{id?}', [SubCategoryController::class, 'update'])->name('save_update_sub_category');

    Route::post('/delete/sub_category/{id?}', [SubCategoryController::class, 'destroy'])->name('delete_sub_category');

    Route::get('/show/sub_category/{id?}', [SubCategoryController::class, 'show'])->name('show_sub_category');


    Route::get('/view/Tracker-Main-System/vaccinees/transaction_summary/{id?}', [VaccineeController::class, 'viewTransact'])->name('view_transaction_summary');


    //END OF TRACKER MAIN SYSTEM
});

vaxtrace/resources/views/Vaxtracing/admin/CreatePermission/index.blade.php
@extends('Vaxtracing.layout.admin.app')

@section('title', 'Create Permission')

@section('content')


<div class="block">
    <ul class="nav nav-tabs nav-tabs-block" data-toggle="tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" href="#btabs-animated-slideleft-master-list">Create Permission</a>
      </li>
    
      <li class="nav-item ml-auto">
        <div class="block-options mr-15 mt-10">
          <button type="button" class="btn-block-option" data-toggle="block-option" data-action="fullscreen_toggle"></button>
          <button type="button" class="btn-block-option" data-toggle="block-option" data-action="state_toggle" data-action-mode="demo">
            <i class="si si-refresh"></i>
          </button>
        </div>
      </li>
    </ul>  
    <div class="block-content tab-content overflow-hidden">
      <div class="tab-pane fade fade-left show active" id="btabs-animated-slideleft-master-list" role="tabpanel">
               <!-- Dynamic Table Full -->
               <div class="block">
                    <div class="block-content">
                      <form role="form" id="formCreatePerm" novalidate>
                        <div class="col-lg-12">
                            <div class="row g-2">
                                <div class="col-12">
                                    <br>
                                    <div class="form-material form-material-success floating">
                                        <input class="js-maxlength form-control" id="example-material-maxlength7 home_address" type="text" name="permission_name"   rows="3" maxlength="100" data-always-show="true" required/>
                                        <label for="example-material-maxlength7" style="font-size: 13px;">Permission Name</label>
                                        <span class="text-danger errorMessage" id="error_home_address"></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <br>
                            <div class="col">
                                <div class="form-material form-material-success floating">
                                    <select class="js-select2 form-control" id="example-select2" name="subsystem" style="width: 100%;" >
                                      @foreach ($subsystems as $subsystem)
                                          <option value="{{ $subsystem->id }}">{{ $subsystem->title }}</option>
                                      @endforeach
                                    </select>
                                    <label for="material-color-select2" style="font-size: 13px;">Sub-system </label>
                                    <span class="text-danger errorMessage fs--2" id="error_region"></span>
                                    
                                </div>
                            </div>
                      </form>
                    </div>

                    <div class="row text-center mt-4">
                        <div class="col-md-2 justify-content-center ml-auto">
                            <div class="block mr-15 ml-15">
                                <button class="btn btn-square btn-alt-success min-width-120 " id="create_permission">Submit <span class="si si-arrow-right ms-2"> </span></button>
                            </div>
                        </div>
                    </div>


                    </form>
                
            </div>
            <!-- END User Profile -->
    </div>
    </div>
<!-- END Block Tabs Animated Slide Left -->
@section('scripts')
    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            let validatorCreatePerm = $('#formCreatePerm').jbvalidator({
                    errorMessage: true,
                    successClass: false,
                });

            $('#create_permission').click(function (e) {
                e.preventDefault();

                var form = document.getElementById("formCreatePerm");
                var formData = new FormData(form);
                if(validatorCreatePerm.checkAll() == 0){
                    $.ajax({
                        url: "{{ route('permission.store') }}",
                        data: formData,
                        cache: false,
                        processData: false,
                        contentType: false,
                        type: 'POST',
                        beforeSend: function () {
                            showLoader();
                        },
                        complete: function () {
                            hideLoader();
                        },
                        success: function (response) {
                            Swal.fire({
                                title: 'Success!',
                                icon: 'success',
                                text: "A new record has been created",
                                confirmButtonText: 'Ok',
                            }).then((result) => {
                                /* Read more about isConfirmed, isDenied below */
                                if (result.isConfirmed) {
                                window.location.href = "{{ route('view_permission') }}";
                                }
                            })
                        },
                        error: function(response){
                            $('.errorMessage').text("");
                            $.each(response.responseJSON.errors,function(field_name,error){            
                                $(document).find('[id=error_'+field_name+']').text("*"+error)
                            })
                        }
                    });
                }
            });
            

            $(".dataTables_filter").hide(); 
        });
    </script>
@endsection
@endsection