vaxtrace/routes/web.php
<?php

use App\Http\Controllers\Vaxtracing\Auth\AuthController;
use App\Http\Controllers\Vaxtracing\JsonDataController;
use App\Http\Controllers\Vaxtracing\CategoryController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Vaxtracing\PeopleController;
use App\Http\Controllers\Vaxtracing\DashboardController;
use App\Http\Controllers\Vaxtracing\PermissionController;
use App\Http\Controllers\Vaxtracing\RoleController;
use App\Http\Controllers\Vaxtracing\SubCategoryController;
use App\Http\Controllers\Vaxtracing\SubSystemController;
use App\Http\Controllers\Vaxtracing\VaccineeController;
use App\Http\Middleware\AuthCheck;
use App\Models\Vaxtracing\Role;
use App\Models\Vaxtracing\Summary;
use App\Models\Vaxtracing\User;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { 
    if(session()->has('LoggedUser')){
        return redirect('/dashboard');
    }
    return view('index'); 
})->name('home');

// Auth
Route::post("/check", [AuthController::class, "login"])->name('submit-login');

Route::get('/logout', [AuthController::class, "logout"])->name('logout');

Route::get('/user-login', [AuthController::class, "view_login"])->name('view-login');
//MIDDLEWARE
Route::group(['middleware' => ['AuthCheck']],function(){
    

    //DASHBOARD
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('get_admin_dashboard');

    //MANAGER USER
    Route::get('/manage/user',function () {
        abort_if(! session('LoggedUser')->hasPermission('USER_ACCESS'), 403);
        return view('Vaxtracing.admin.ManageUser.index');
    })->name('get_manage_user');
  
    
    Route::resource('people', PeopleController::class);

    Route::get('/create/user', function () {
        abort_if(! session('LoggedUser')->hasPermission('USER_CREATE'), 403);
        $total_role = Role::get();
        return view('Vaxtracing.admin.CreatePerson.index', compact('total_role'));
    })->name('get_create_user');

    Route::get('/update/user', function () {
        abort_if(! session('LoggedUser')->hasPermission('USER_UPDATE'), 403);
        $total_role = Role::get();
        return view('Vaxtracing.admin.UpdatePerson.index', compact('total_role'));
    })->name('get_update_user');

    //Generate address
    Route::get("/create/get_address", [JsonDataController::class, "index"])->name('get_address');

    Route::get("/get-activity-logs", [JsonDataController::class, "getActivity"])->name('get_activity');


    Route::get("/get-vaccinees", [JsonDataController::class, "getVaccinees"])->name('get_vaccinees');

    //Change Password
    Route::post('/change/password/', [PeopleController::class, 'changePassword'])->name('change_password');

    // List of user
    Route::post("/create/people", [PeopleController::class, "store"]);

    Route::get("/show/people", [PeopleController::class, "index"])->name('get_people');

    Route::get("/show/deleted_people", [PeopleController::class, "showDeletedPeople"])->name('get_deleted_people');

    Route::get("/show/restored_people", [PeopleController::class, "showRestoredPeople"])->name('get_restored_people');

    Route::get('/show/people/{user_id?}', [PeopleController::class, 'show'])->name('show_people');

    Route::get('/update/people/{user_id?}', [PeopleController::class, 'edit'])->name('update_people');

    Route::post('/update/people/save/{user_id?}', [PeopleController::class, 'update'])->name('save_update_people');

    Route::post('/delete/people/{user_id?}', [PeopleController::class, 'destroy'])->name('delete_people');

    Route::post('/restore/people/{user_id?}', [PeopleController::class, 'restore'])->name('restore_people');


    Route::view('/edit/profile', 'Vaxtracing.admin.EditProfile.index')->name('edit_profile');

    Route::post('/edit/profile/save/{user_id?}', [PeopleController::class, 'editProfile'])->name('save_edit_profile');

    Route::get('/view/activity_log',  function () {
        abort_if(! session('LoggedUser')->hasPermission('ACTIVITY_ACCESS'), 403);
        return view('Vaxtracing.admin.ActivityLog.index');
    })->name('view_activity_log');

    Route::get('/view/department', function () {
        abort_if(! session('LoggedUser')->hasPermission('ROLE_ACCESS'), 403);
        return view('Vaxtracing.admin.Department.index');
    })->name('view_department');
    
    Route::get('/view/permission', function () {
        abort_if(! session('LoggedUser')->hasPermission('PERMISSION_ACCESS'), 403);
        return view('Vaxtracing.admin.Permission.index');
    })->name('view_permission');

    Route::get('/view/subsystem', function () {
        abort_if(! session('LoggedUser')->hasPermission('SUBSYSTEM_ACCESS'), 403);
        return view('Vaxtracing.admin.Subsystem.index');
    })->name('view_subsystem');

    // Route::view('/create/department', 'Vaxtracing.admin.CreateDepartment.index')->name('get_create_department');

    //Route::view('/create/permission', 'Vaxtracing.admin.CreatePermission.index')->name('get_create_permission');

    //MANAGE PERMISSION

    Route::resource('role', RoleController::class);

    Route::get('/update/role/{id?}', [RoleController::class, 'edit'])->name('update_department');

    Route::post('/update/role/save/{id?}', [RoleController::class, 'update'])->name('save_update_department');

    Route::post('/delete/role/{id?}', [RoleController::class, 'destroy'])->name('delete_department');

    Route::get("/show/role/{id?}", [RoleController::class, "show"])->name('show_role');

    //MANAGE PERMISSION

    Route::resource('permission', PermissionController::class);

    Route::get('/update/permission/{id?}', [PermissionController::class, 'edit'])->name('update_permission');

    Route::post('/update/permission/save/{id?}', [PermissionController::class, 'update'])->name('save_update_permission');

    Route::post('/delete/permission/{id?}', [PermissionController::class, 'destroy'])->name('delete_permission');

    //MANAGE SUBSYSTEM

    Route::resource('subsystem', SubSystemController::class);

    Route::get('/update/subsystem/{id?}', [SubSystemController::class, 'edit'])->name('update_subsystem');

    Route::post('/update/subsystem/save/{id?}', [SubSystemController::class, 'update'])->name('save_update_subsystem');

    Route::post('/delete/subsystem/{id?}', [SubSystemController::class, 'destroy'])->name('delete_subsystem');


    //TRACKER MAIN SYSTEM

    Route::get('/view/Tracker-Main-System/vaccinees/VaccineeMasterList', function () {
        abort_if(! session('LoggedUser')->hasPermission('VACCINEE_ACCESS'), 403);
        $summaries = DB::table('transaction_has_summary')->select('assist_by')->distinct()->get();
       
        return view('Vaxtracing.admin.TrackingSystem.VaccineeMasterList.index', compact('summaries'));
    })->name('view_vaccinees_VaccineeMasterList');
    

    Route::resource('vaccinee', VaccineeController::class);

    Route::post('/update/vaccinee/save/{id?}', [VaccineeController::class, 'update'])->name('save_update_vaccinee');

    Route::post('/delete/vaccinee/{id?}', [VaccineeController::class, 'destroy'])->name('delete_vaccinee');

    Route::get('/show/vaccinee/{id?}', [VaccineeController::class, 'show'])->name('show_vaccinee');

    Route::get('/monitor/vaccinee/{id?}', [VaccineeController::class, 'monitor'])->name('monitor_vaccinee');

    Route::get('/show/summary/{id?}', [VaccineeController::class, 'showSummary'])->name('show_summary');

    Route::get('/show/transaction/{vaccinee_id?}/{id?}', [VaccineeController::class, 'showTransaction'])->name('show_transaction');

    Route::post('/save/vaccinee/transaction', [VaccineeController::class, 'saveTransaction'])->name('save_vaccinee_transaction');

    Route::post('/save/update/vaccinee/transaction', [VaccineeController::class, 'saveUpdateTransaction'])->name('save_update_transaction');

    Route::get('/show/all/summary/{date_from?}/{date_to?}', [VaccineeController::class, 'showSummaryLogs'])->name('show_summary_logs');

    Route::get('/view/Tracker-Main-System/vaccinees/status/category', function () {
        return view('Vaxtracing.admin.TrackingSystem.Category.index');
    })->name('view_vaccinees_status_category');

    Route::resource('category', CategoryController::class);

    Route::post('/update/category/save/{id?}', [CategoryController::class, 'update'])->name('save_update_category');

    Route::post('/delete/category/{id?}', [CategoryController::class, 'destroy'])->name('delete_category');

    Route::get('/show/category/{id?}', [CategoryController::class, 'show'])->name('show_category');

    Route::get('/view/Tracker-Main-System/vaccinees/status/sub-category/{category_id?}', function ($category_id) {
        session()->put('current_category', $category_id);
        return view('Vaxtracing.admin.TrackingSystem.SubCategory.index',compact('category_id'));
    })->name('view_vaccinees_status_sub-category');

    Route::resource('sub_category', SubCategoryController::class);

    Route::post('/update/sub_category/save/{id?}', [SubCategoryController::class, 'update'])->name('save_update_sub_category');

    Route::post('/delete/sub_category/{id?}', [SubCategoryController::class, 'destroy'])->name('delete_sub_category');

    Route::get('/show/sub_category/{id?}', [SubCategoryController::class, 'show'])->name('show_sub_category');


    Route::get('/view/Tracker-Main-System/vaccinees/transaction_summary/{id?}', [VaccineeController::class, 'viewTransact'])->name('view_transaction_summary');


    //END OF TRACKER MAIN SYSTEM
});

vaxtrace/app/Models/Vaxtracing/SubSystem.php
<?php

namespace App\Models\Vaxtracing;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SubSystem extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
    ];
}

vaxtrace/app/Http/Controllers/Vaxtracing/SubSystemController.php
<?php

namespace App\Http\Controllers\Vaxtracing;

use App\Http\Controllers\Controller;
use App\Models\Vaxtracing\SubSystem;
use Illuminate\Http\Request;
use DataTables;

class SubSystemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        abort_if(! session('LoggedUser')->hasPermission('SUBSYSTEM_ACCESS'), 403);
        if ($request->ajax()) {
            $data = SubSystem::get();

            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $actionBtn = "";
                    if(session('LoggedUser')->hasPermission('SUBSYSTEM_VIEW')){
                        $actionBtn .= " <a class='view btn btn-alt-primary btn-rounded mr-5 mb-5' onclick='show_subsystem($row->id)'><i class='si si-eye mr-5'></i>View</button></a>";
                    }
                    if(session('LoggedUser')->hasPermission('SUBSYSTEM_UPDATE')){
                        $actionBtn .= "<a href='".route('update_subsystem', $row->id)."' class='update btn btn-alt-success btn-rounded mr-5 mb-5'><i class='si si-pencil mr-5'></i>Update</a>";
                    }
                    if(session('LoggedUser')->hasPermission('SUBSYSTEM_DELETE')){
                        $actionBtn .= "<a class='delete delete btn btn-alt-danger btn-rounded mr-5 mb-5' onclick='delete_subsystem($row->id)'><i class='si si-trash mr-5'></i>Delete</a>";
                    }
            
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(! session('LoggedUser')->hasPermission('SUBSYSTEM_CREATE'), 403);
        return view('Vaxtracing.admin.CreateSubsystem.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        abort_if(! session('LoggedUser')->hasPermission('SUBSYSTEM_CREATE'), 403);
        $role = new SubSystem();
        $role->title = formatString($request->subsystem_name);
        $role->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        abort_if(! session('LoggedUser')->hasPermission('SUBSYSTEM_UPDATE'), 403);
        $subsystem = SubSystem::find($id);

        return view('Vaxtracing.admin.UpdateSubsystem.index', compact('subsystem'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        abort_if(! session('LoggedUser')->hasPermission('SUBSYSTEM_UPDATE'), 403);
        $role = SubSystem::find($id)
            ->update([
                'title'=> formatString($request->subsystem_name),
            ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        abort_if(! session('LoggedUser')->hasPermission('SUBSYSTEM_DELETE'), 403);
        $subsystem = SubSystem::find($id)->delete();
    }
}

vaxtrace/resources/views/Vaxtracing/admin/Subsystem/index.blade.php
@extends('Vaxtracing.layout.admin.app')

@section('title', 'Subsystem')

@section('content')


<div class="block">
    <ul class="nav nav-tabs nav-tabs-block" data-toggle="tabs" role="tablist">
        <li class="nav-item">
        <a class="nav-link active" href="#btabs-animated-slideleft-master-list">Subsystem List</a>
        </li>
        <li class="nav-item ml-auto">
        <div class="block-options mr-15 mt-10">
            <button type="button" class="btn-block-option" data-toggle="block-option" data-action="fullscreen_toggle"></button>
            <button type="button" class="btn-block-option" data-toggle="block-option" data-action="state_toggle" data-action-mode="demo">
            <i class="si si-refresh"></i>
            </button>
        </div>
        </li>
    </ul> 
    <div class="row text-center">
        <div class="col-md-3">
        <div class="block">
            <div class="block-content">
            <form class="row align-items-center g-3">
                <div class="col-md-auto position-relative">
                <a class="btn btn-hero btn-alt-primary mr-5 mb-5 btn-block" type="button" href="{{ route('subsystem.create') }}"><i class="fa fa-plus mr-5"></i>Add Subsystem</a> 
                </div>
            </form>
            </div>
        </div>
        </div>
        <div class="col-md-6 justify-content-center ml-auto">
        <div class="block mr-15 ml-15">
            <div class="form-material floating input-group form-material-primary">
            <input type="text" class="form-control" id="search_bar" name="material-color-success2">
            <label for="material-color-success2">Search here...</label>
            <div class="input-group-append">
                <button type="button" class="view" id="search_btn" style="background: none; border:none">
                <i class="si si-magnifier"></i>     
                </button>
            </div>
            </div>
        </div>
        </div>
    </div>
    <div class="table-responsive scrollbar p-3">
        <table class="table table-striped table-center js-dataTable-full-pagination" id="subsystem_dt" width="100%">
            <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
</div>
<!-- END Table Sections -->
@section('scripts')
<script type="text/javascript">

$(function () {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    //MASTER LIST
    var table = $('#subsystem_dt').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('subsystem.index') }}",
        columns: [
            //TITLE
            {data: 'title'},
            //ACTION
            {data: 'action'},
        ]  
    });
    $('#search_btn').on('click', function(){
            table.search($('#search_bar').val().toUpperCase()).draw();
        })
    $(".dataTables_filter").hide(); 
});
function delete_subsystem(id){
    Swal.fire({
        title: 'Do you want to delete this subsystem?',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Yes',
        backdrop: `
        rgba(0,0,123,0.4)
        left top
        no-repeat
        `,
    }).then((result) => {
        /* Read more about isConfirmed, isDenied below */
        if (result.isConfirmed) {
            $.ajax({
                type: "POST",
                url: "{{ route('delete_subsystem') }}"+'/'+id,
                processData: false,
                contentType: false,
                beforeSend: function () {
                    showLoader();
                },
                complete: function () {
                    hideLoader();
                },
                success: function (response) {
                    Swal.fire({
                        title: 'Success!',
                        icon: 'success',
                        text: "The subsystem has been deleted",
                        confirmButtonText: 'Ok',
                        backdrop: `
                        rgba(0,0,123,0.4)
                        left top
                        no-repeat
                        `,
                    }).then((result) => {
                        /* Read more about isConfirmed, isDenied below */
                        if (result.isConfirmed) {
                            location.reload();
                        }
                    })
                },
                error: function (response) {
                    hideLoader();
                }
            }); 
        } else{
        
        }
    })
}
</script>
@endsection
@endsection